INSERT INTO CUSTOMERS (ID,GIVEN_NAME,SURNAME) VALUES (1,'MOHIT', 'KANWAR');
INSERT INTO CUSTOMERS (ID,GIVEN_NAME,SURNAME) VALUES (2,'Virat', 'Kohli');
INSERT INTO CUSTOMERS (ID,GIVEN_NAME,SURNAME) VALUES (3,'Rohit', 'Sharma');
INSERT INTO CUSTOMERS (ID,GIVEN_NAME,SURNAME) VALUES (4,'Sachin', 'Tendulkar');